### PR TITLE
feat: Add Hall of Fame section

### LINKED ISSUE #27: Add Hall of Fame section
- [x] Discuss content that is to be displayed here
- [ ] Discuss and create layout
- [ ] Create `Hall of Fame` collection in firestore
- [ ] Create `fame` module in store. Fetch data from firebase

### PR DESCRIPTION
**Pull request by mohdomama**
fixes #27 
The layout can be improved in future iterations if required.

### CODE REVIEW

**Comment by mohdomama** [comment]
If your are signed in as an editor, you can see the add button

**Review by iamareebjamal — DISMISSED** [review]
WOW. Outstanding

**Comment by iamareebjamal** [comment]
Although, let the admin access be required for the visibility of adding an entry

**Comment by mohdomama** [comment]
Working on it. I have also added `delete entry` functionality. Don't merge!

**Comment by mohdomama** [comment]
I think editors should also have access. Otherwise there will be only one or two people managing this page.

**Comment by iamareebjamal** [comment]
We can increase the roles, editors should only be able to add articles and edit their own articles and manager should manage some bits and admins should be able to control everything?

**Comment by mohdomama** [comment]
@iamareebjamal I have added admin privileges for creating\deleting fame entries but couldn't test (I am not an admin). Please test it.

**Comment by iamareebjamal** [comment]
You could change the role from firebase console :smile:

**Comment by iamareebjamal** [comment]
Deleting storage file is not working. Actually, don't delete the file in code, we will create a firebase function to automatically delete the file once the hall of fame entry is deleted

**Comment by mohdomama** [comment]
Its working for me (Typical developers problem :P) :confused: There were 4 files, I deleted one from the `Hall of Fame` page, now there are three files in firebase.

**Comment by iamareebjamal** [comment]
It was throwing an exception for me.

```
Failed to load resource: the server responded with a status of 404 ()
"storage/object-not-found"
"Firebase Storage: Object 'fame/undefined' does not exist."
```

Try deleting 3rd entry

**Comment by mohdomama** [comment]
That was because that entry was created before the delete feature was added. I made some changes in how things were being referenced in that commit. I have deleted that entry manually from the firebase console. Won't happen with the newer entries. Try it.

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
