### PR TITLE
Changes in layout

### PR DESCRIPTION
**Pull request by mohdomama**
Please refer to https://mohdomama.github.io/#/ before merging.

### CODE REVIEW

**Comment by mohdomama** [comment]
Should I squash the commits ?

**Comment by iamareebjamal** [comment]
Nah, we'll squash using github if required

**Comment by iamareebjamal** [comment]
PR Successfully Deployed : https://pr-8-mohdomama-amu2ias-frontend.surge.sh

**Comment by mohdomama** [comment]
Why are the tests failing ?

**Comment by iamareebjamal** [comment]
It's not failing, the builds triggered twice, so the latest one succeeded and previous one timed out and failed

**Comment by iamareebjamal** [comment]
Successful Build: https://circleci.com/gh/amu-oss/amu2ias-frontend/22?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by iamareebjamal** [comment]
PR Successfully Deployed : https://pr-8-mohdomama-amu2ias-frontend.surge.sh

**Comment by iamareebjamal** [comment]
OK, there are 2 bugs:

1. In menu, if any other section is selected, still the home section is shown to be highlighted
2. The image in About section is not displayed

Another suggestion, don't use static assets in the repository itself, it increases the size because they're binary. Instead, upload the images in Firebase Storage and use the link here

**Comment by iamareebjamal** [comment]
Also, IMO dark nav bar on light site does not look that good. Maybe just keep it light or change the color

**Comment by iamareebjamal** [comment]
Circle CI has gone mad I guess

**Comment by mohdomama** [comment]
Bugs:
   1. I will look into that.
   2. Wrong link

I will add the logo to firebase.
I just copied the default navigation drawer the vutify website was using, will change it sometime. Also by default the navigation drawer was set to true. That is, it always opened when page was reloaded. Is it okay or should i change it back ?

**Comment by iamareebjamal** [comment]
It's OK

**Comment by mohdomama** [comment]
Circle CI is expecting a login ? :confused:

**Comment by iamareebjamal** [comment]
It's older build, ignore. New builds have passed 22, 23, etc. 21 was failed and it is showing that one

Refer to this https://circleci.com/gh/amu-oss/amu2ias-frontend/22?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mohdomama** [comment]
@iamareebjamal Thanks.

**Comment by iamareebjamal** [comment]
PR Successfully Deployed : https://pr-8-mohdomama-amu2ias-frontend.surge.sh

**Comment by mohdomama** [comment]
I have fixed the bugs, changed the color theme of the drawer, added firebse.
@iamareebjamal please take a look at the main.js file. I was trying to get the download url of `static/img/logo.png` with firebase, but its not working. So, as of now, I have hardcoded the download url.

**Comment by mohdomama** [comment]
I have commented out the things I tried to get the download url at runtime (in `main.js`). This will give you an idea of what I was upto.

**Comment by iamareebjamal** [comment]
Yes we have to hardcode. Also, let's not add firebase config in this PR. One PR should handle one issue only

**Comment by iamareebjamal** [comment]
Have you enabled `Allow edits by maintainers`. I'll also take a look and try to finalize

**Comment by mohdomama** [comment]
Okay I will remove firebase config. Working on it.
Yes, I have enabled `Allow edits by maintainers.

**Comment by iamareebjamal** [comment]
PR Successfully Deployed : https://pr-8-mohdomama-amu2ias-frontend.surge.sh

**Comment by mohdomama** [comment]
Lets move towards auth now.

**Comment by iamareebjamal** [comment]
PR Successfully Deployed : https://pr-8-mohdomama-amu2ias-frontend.surge.sh

**Pull request merged**
