### PR TITLE
Add about section, improve basic layout.

### LINKED ISSUE #21: Implement About section
- [x] Use global collection to add about document
- [x] Populate necessary fields in about document
- [x] Discuss and design page layout
- [x] Bind firebase document to page

### PR DESCRIPTION
**Pull request by mohdomama**
fixes #21

### CODE REVIEW

**Comment by mohdomama** [comment]
@iamareebjamal please take a look at the layout. Later I will fetch content from firebase.

**Comment by mohdomama** [comment]
Also don't you think that the blogs page looks too greyish ? Should I change some colors ?

**Comment by iamareebjamal** [comment]
Add a color property in the blog document and render it from there

**Comment by iamareebjamal** [comment]
Also, create a new PR as this is merged

**Comment by iamareebjamal** [comment]
@mohdomama Great color scheme, though change menu from dark to light

**Comment by mohdomama** [comment]
I have created a standalone module of about page in store instead of populating the global store. I thought it would be better since we will need feedback methods in the same?.  Also for feedback, I am thinking of creating a new collection and each feedback will be a document in that collection. Should we allow feedback from any user or only the signed in ?

**Comment by iamareebjamal** [comment]
No, feedback should be anonymous

**Review by iamareebjamal — DISMISSED** [review]

**Comment by mohdomama** [comment]
@iamareebjamal can you please add a firebase `postFeedback` in form submit method. That will be in `src/components/about/feedback.vue`. I am having some issues :sweat_smile: And I think i have overwritten some of your changes :rofl:

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
