### PR TITLE
Add render blog functionality

### LINKED ISSUE #16: Render blogs from /blogs collection
- [x] Populate collection with dummy data
- [x] Add blogs module in Vuex Store
- [x] Add blogs component 
- [x] Load blogs and render

### PR DESCRIPTION
**Pull request by mohdomama**
fixes #16

### CODE REVIEW

**Comment by mohdomama** [comment]
@iamareebjamal I have made it work somehow. I am not sure I followed all the good practices. Please take a look at store/blog

**Comment by mohdomama** [comment]
@iamareebjamal did you create some blank enteries in the blogs collection ? Apart from that `Test Blog` entry ?

**Comment by iamareebjamal** [comment]
Yes, I'm currently working on pagination

**Comment by mohdomama** [comment]
@iamareebjamal can we merge this ?

**Comment by mohdomama** [comment]
Also as on now, entire data in blogs collection is fetched at once, this can be problematic if the blogs are too many. What I was thinking was that we should separate meta data (Titile, author, category, tags, time, small description, Link to the blog page) and the actual content of the blog. The metadata will be fetched at once on page load. It will contain the link of the actual page. That page can be accessed by clicking `read more` ?

**Comment by iamareebjamal** [comment]
`Yes, I'm currently working on pagination` 
Pagination will only load about 10 items and other items will be loaded by next and previous buttons

Pagination is a little difficult in firestore, I'm working on it with a little workaround

**Review by iamareebjamal — APPROVED** [review]

**Comment by mohdomama** [comment]
Great work @iamareebjamal . Btw  sorry for ranting :sweat_smile:

**Comment by iamareebjamal** [comment]
Arey criticism what I cherish

**Pull request merged**
